sudo: false
language: ruby
rvm:
  - 2.7.0

cache:
  bundler: true
  directories:
  - $HOME/libsodium

before_install: gem install bundler -v 2.1.0

install:
  - ./travis-install-libsodium.sh
  - ./travis-install-configfile.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
  - bundle install
